version: '2'
volumes:
  volume_byodr:
  volume_config:
  volume_recorder:
services:
  vehicle:
    build:
      context: .
      dockerfile: vehicles/carla09/Dockerfile
    image: centipede2donald/byodr-ce:carla-099
    container_name: byodr_vehicle
    environment:
      LD_PRELOAD: libgomp.so.1
    volumes:
      - volume_byodr:/byodr:rw
      - volume_config:/config:ro
      - ./common:/common
      - ./vehicles/carla09:/app
  teleop:
    build:
      context: .
      dockerfile: teleop/Dockerfile
    image: centipede2donald/byodr-ce:teleop
    container_name: byodr_teleop
    ports:
      - "80:9100"
    environment:
      LD_PRELOAD: libgomp.so.1
    volumes:
      - volume_byodr:/byodr:rw
      - volume_config:/config:rw
      - ./common:/common
      - ./teleop:/app
  pilot:
    build:
      context: .
      dockerfile: pilot/Dockerfile
    image: centipede2donald/byodr-ce:pilot
    container_name: byodr_pilot
    environment:
      LD_PRELOAD: libgomp.so.1
    volumes:
      - volume_byodr:/byodr:rw
      - volume_config:/config:ro
      - ./common:/common
      - ./pilot:/app
  recorder:
    build:
      context: .
      dockerfile: recorder/Dockerfile
    image: centipede2donald/byodr-ce:recorder
    container_name: byodr_recorder
    environment:
      LD_PRELOAD: libgomp.so.1
    volumes:
      - volume_byodr:/byodr:rw
      - volume_config:/config:ro
      - volume_recorder:/sessions:rw
      - ./common:/common
      - ./recorder:/app
  inference:
    build:
      context: .
      dockerfile: inference/Dockerfile.x86
    image: centipede2donald/byodr-ce:inference-carla
    container_name: byodr_inference
    environment:
      - LD_PRELOAD=libgomp.so.1
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - volume_byodr:/byodr:rw
      - volume_config:/config:ro
      - ./common:/common
      - ./inference:/app
