version: '2'
services:
  ros-master:
    image: ros:melodic
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore
  pilot:
    build:
      context: ./pilot
      dockerfile: Dockerfile
    image: byodr/pilot
    container_name: byodr_pilot
    volumes:
      - './pilot:/app'
    environment:
      ROS_MASTER_URI: 'http://ros-master:11311'
    command: python pilot.py --config=/app/${DC_PILOT_CONFIG} --clock=${DC_PILOT_HZ}
  teleop:
    build:
      context: ./teleop
      dockerfile: Dockerfile
    image: byodr/teleop
    container_name: byodr_teleop
    ports:
      - "9100:9100"
    volumes:
      - './teleop:/app'
      - '/tmp/byodr:/tmp/byodr'
    environment:
      ROS_MASTER_URI: 'http://ros-master:11311'
      TELEOP_HOME: '/app'
    command: python teleop.py --port=9100
  vehicle:
    build:
      context: ./vehicles/carla09
      dockerfile: Dockerfile
      args:
        app_uid: ${DC_APP_UID}
    image: byodr/vehicle_carla
    container_name: byodr_carla
    volumes:
      - './vehicles/carla09:/app'
      - '/tmp/byodr:/tmp/byodr'
    environment:
      ROS_MASTER_URI: 'http://ros-master:11311'
    command: python core.py --remote=${DC_CARLA_REMOTE}


