version: '2'
services:
  teleop:
    user: '1000'
    build:
      context: ./teleop
      dockerfile: Dockerfile
    image: byodr/teleop
    container_name: byodr_teleop
    ports:
      - "9100:9100"
    volumes:
      - './teleop:/app'
      - '/tmp/byodr:/tmp/byodr'
    environment:
      TELEOP_HOME: '/app'
    command: python app.py --port=9100
  pilot:
    user: '1000'
    build:
      context: ./pilot
      dockerfile: Dockerfile
    image: byodr/pilot
    container_name: byodr_pilot
    volumes:
      - './pilot:/app'
      - '/tmp/byodr:/tmp/byodr'
    command: python app.py --config=/app/${DC_PILOT_CONFIG} --clock=${DC_PILOT_HZ}
  inference:
    user: '1000'
    build:
      context: ./inference
      dockerfile: Dockerfile
    image: byodr/inference
    container_name: byodr_inference
    volumes:
      - './inference:/app'
      - '/tmp/byodr:/tmp/byodr'
      - '/data1/Models:/data1/Models'
    environment:
      CADEN_DNN: ${DC_CADEN_DNN}
    command: python app.py --gpu=${DC_CADEN_GPU} --clock=${DC_INFERENCE_HZ}
  vehicle:
    user: '1000'
    build:
      context: ./vehicles/carla09
      dockerfile: Dockerfile
    image: byodr/vehicle_carla
    container_name: byodr_carla
    volumes:
      - './vehicles/carla09:/app'
      - '/tmp/byodr:/tmp/byodr'
    command: python app.py --remote=${DC_CARLA_REMOTE}


