version: '2'
services:
  teleop:
    volumes:
      - ./common:/common
      - ./teleop:/app
  pilot:
    volumes:
      - ./common:/common
      - ./pilot:/app
  recorder:
    volumes:
      - ./common:/common
      - ./recorder:/app
  ros:
    image: centipede2donald/byodr-ce:rosserial
    container_name: byodr_ros
    command: roscore
    ports:
      - "11311:11311"
  rosserial:
    build:
      context: .
      dockerfile: vehicles/rover/Dockerfile.ros
    image: centipede2donald/byodr-ce:rosserial
    command: python rosserial.py --port=/dev/arduino
    environment:
      ROS_MASTER_URI: 'http://byodr_ros:11311'
    volumes:
      - ./vehicles/rover:/app
    devices:
      - /dev/arduino
  vehicle:
    build:
      context: .
      dockerfile: vehicles/rover/Dockerfile
    image: centipede2donald/byodr-ce:rover
    environment:
      ROS_MASTER_URI: 'http://byodr_ros:11311'
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
  inference:
    build:
      context: ./
      dockerfile: inference/Dockerfile.jp
    image: centipede2donald/byodr-ce:inference
    volumes:
      - './inference:/app'
      - '/usr/local/cuda:/usr/local/cuda'
      - '/usr/lib/aarch64-linux-gnu:/usr-extra'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'


