version: '2'
services:
  cam1:
    image: centipede2donald/byodr-ce:rover
    restart: always
    command: python stream.py
    stop_signal: SIGKILL
  nodews:
    image: centipede2donald/byodr-ce:nodews
    restart: always
    depends_on:
      - "cam1"
    ports:
      - "9101:9101"
    environment:
      FEED_IP: 'byodr_cam1'
    stop_signal: SIGKILL
#  ros:
#    image: centipede2donald/byodr-ce:rosserial
#    restart: always
#    command: roscore
#    ports:
#      - "11311:11311"
#  rosserial:
#    image: centipede2donald/byodr-ce:rosserial
#    restart: always
#    command: python rosserial.py --port=/dev/arduino
#    environment:
#      ROS_MASTER_URI: 'http://byodr_ros:11311'
#    devices:
#      - /dev/arduino
  vehicle:
    image: centipede2donald/byodr-ce:rover
    restart: always
    environment:
      ROS_MASTER_URI: 'http://raspberrypi.local:11311'
  inference:
    image: centipede2donald/byodr-ce:inference
    restart: always
    volumes:
      - '/usr/local/cuda:/usr/local/cuda'
      - '/usr/lib/aarch64-linux-gnu:/usr-extra'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'


