version: '2'
services:
  zerotier:
    image: rwgrim/docker-noop:latest
    restart: 'no'
  relay:
    image: rwgrim/docker-noop:latest
    restart: 'no'
  cam1:
    image: rwgrim/docker-noop:latest
    restart: 'no'
  nodews:
    image: rwgrim/docker-noop:latest
    restart: 'no'
  vehicle:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
  teleop:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./teleop:/app
  pilot:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./pilot:/app
  recorder:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./recorder:/app
  inference:
    restart: 'no'
    command: ["python", "-m", "pytest", "-vvv", "tests.py"]
    volumes:
      - ./common:/common
      - ./inference:/app
