version: '2'
services:
  rosserial:
    user: '1000'
    image: centipede2donald/byodr-ce:ros-serial
    devices:
      - /dev/ttyACM0
    ports:
      - "11311:11311"
    command: roslaunch rosserial.launch
  teleop:
    user: '1000'
    image: centipede2donald/byodr-ce:teleop
    ports:
      - "9100-9105:9100-9105"
    volumes:
      - ${DC_CONFIG_DIR}:/config
    environment:
      TELEOP_HOME: '/app'
    command: python app.py --port=9100 --config=/config
  pilot:
    user: '1000'
    image: centipede2donald/byodr-ce:pilot
    volumes:
      - volume_byodr:/byodr
      - ${DC_CONFIG_DIR}:/config
    command: python app.py --config=/config
  recorder:
    user: '1000'
    image: centipede2donald/byodr-ce:recorder
    volumes:
      - volume_byodr:/byodr
      - ${DC_CONFIG_DIR}:/config
      - ${DC_RECORDER_SESSIONS}:/sessions
    command: python app.py --sessions=/sessions --config=/config
  inference:
    user: '1000'
    runtime: nvidia
    image: centipede2donald/byodr-ce:inference
    volumes:
      - volume_byodr:/byodr
      - '/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu'
      - '/usr/local/cuda-10.0:/usr/local/cuda'
      - ${DC_CONFIG_DIR}:/config
    command: python app.py --models=/models --config=/config
  vehicle:
    user: '1000'
    image: centipede2donald/byodr-ce:vehicle-rover
    volumes:
      - volume_byodr:/byodr
      - ${DC_CONFIG_DIR}:/config
    environment:
      ROS_MASTER_URI: 'http://byodr_rover_ros:11311'
    command: python app.py --config=/config


