version: '2'
volumes:
  volume_byodr:
services:
  teleop:
    build:
      context: ./
      dockerfile: teleop/Dockerfile
    image: centipede2donald/byodr-ce:teleop
    ports:
      - "9100-9105:9100-9105"
    volumes:
      - volume_byodr:/byodr
      - ./common:/common
      - ./teleop:/app
      - ${DC_CONFIG_DIR}:/config
  pilot:
    build:
      context: ./
      dockerfile: pilot/Dockerfile
    image: centipede2donald/byodr-ce:pilot
    volumes:
      - volume_byodr:/byodr
      - ./common:/common
      - ./pilot:/app
      - ${DC_CONFIG_DIR}:/config
  recorder:
    build:
      context: ./
      dockerfile: recorder/Dockerfile
    image: centipede2donald/byodr-ce:recorder
    volumes:
      - volume_byodr:/byodr
      - ./common:/common
      - ./recorder:/app
      - ${DC_CONFIG_DIR}:/config
      - ${DC_RECORDER_SESSIONS}:/sessions
  inference:
    image: centipede2donald/byodr-ce:inference
    volumes:
      - volume_byodr:/byodr
      - ./common:/common
      - ./inference:/app
      - ${DC_CONFIG_DIR}:/config


