version: '2'
services:
  teleop:
    build:
      context: .
      dockerfile: teleop/Dockerfile
    image: centipede2donald/byodr-ce:teleop
    ports:
      - "9100:9100"
    volumes:
      - ${DC_CONFIG_DIR}:/config
  pilot:
    build:
      context: .
      dockerfile: pilot/Dockerfile
    image: centipede2donald/byodr-ce:pilot
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw
  recorder:
    build:
      context: .
      dockerfile: recorder/Dockerfile
    image: centipede2donald/byodr-ce:recorder
    volumes:
      - ${DC_CONFIG_DIR}:/config
      - ${DC_RECORDER_SESSIONS}:/sessions
    volumes_from:
      - teleop:rw
  rosserial:
    image: rwgrim/docker-noop:latest
  vehicle:
    image: rwgrim/docker-noop:latest
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw
  inference:
    image: rwgrim/docker-noop:latest
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw


