version: '2'
services:
  zerotier:
    image: rwgrim/docker-noop:latest
  relay:
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
  cam1:
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
  vehicle:
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
  teleop:
    volumes:
      - ./common:/common
      - ./teleop:/app
  pilot:
    volumes:
      - ./build/pytest_cache:/pytest_cache
      - ./common:/common
      - ./pilot:/app
  recorder:
    volumes:
      - ./common:/common
      - ./recorder:/app
  inference:
    volumes:
      - ./common:/common
      - ./inference:/app
