version: '2'
services:
  cam1:
    image: rwgrim/docker-noop:latest
    container_name: byodr_cam1
  nodews:
    build:
      context: .
      dockerfile: teleop/nodews/Dockerfile
    image: centipede2donald/byodr-ce:nodews
    container_name: byodr_nodews
    restart: on-failure
    depends_on:
      - "cam1"
    ports:
      - "9101:9101"
    stop_signal: SIGKILL
  teleop:
    build:
      context: .
      dockerfile: teleop/Dockerfile
    image: centipede2donald/byodr-ce:teleop
    container_name: byodr_teleop
    restart: on-failure
    ports:
      - "9100:9100"
    volumes:
      - ${DC_CONFIG_DIR}:/config
  pilot:
    build:
      context: .
      dockerfile: pilot/Dockerfile
    image: centipede2donald/byodr-ce:pilot
    container_name: byodr_pilot
    restart: on-failure
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw
  recorder:
    build:
      context: .
      dockerfile: recorder/Dockerfile
    image: centipede2donald/byodr-ce:recorder
    container_name: byodr_recorder
    restart: on-failure
    volumes:
      - ${DC_CONFIG_DIR}:/config
      - ${DC_RECORDER_SESSIONS}:/sessions
    volumes_from:
      - teleop:rw
  ros:
    image: rwgrim/docker-noop:latest
    container_name: byodr_ros
  rosserial:
    image: rwgrim/docker-noop:latest
    container_name: byodr_rosserial
    depends_on:
      - "ros"
  vehicle:
    image: rwgrim/docker-noop:latest
    container_name: byodr_vehicle
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw
  inference:
    image: rwgrim/docker-noop:latest
    container_name: byodr_inference
    volumes:
      - ${DC_CONFIG_DIR}:/config
    volumes_from:
      - teleop:rw


