version: '2'
services:
  rosserial:
    user: '1000'
    build:
      context: ./vehicles/rover
      dockerfile: Dockerfile.rosserial
    image: byodr/vehicle_rover_ros
    container_name: byodr_rover_ros
    volumes:
      - './vehicles/rover:/app'
    devices:
      - '/dev/ttyACM0'
    ports:
      - "11311:11311"
    command: roslaunch rosserial.launch
  inference:
    volumes:
      - './inference:/app'
      - '/tmp/byodr:/tmp/byodr'
      - '/mnt/data1:/data1'
      - '/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra'
      - '/usr/local/cuda-9.0:/usr/local/cuda'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    user: '1000'
    build:
      context: ./vehicles/rover
      dockerfile: Dockerfile.rover
    image: byodr/vehicle_rover
    container_name: byodr_rover
    volumes:
      - './vehicles/rover:/app'
      - '/tmp/byodr:/tmp/byodr'
    environment:
      ROS_MASTER_URI: 'http://byodr_rover_ros:11311'
    command: python app.py --config=/app/${DC_JSON_CONFIG} --clock=${DC_VEHICLE_HZ}


