version: '2'
services:
  inference:
    volumes:
      - './inference:/app'
      - '/tmp/byodr:/tmp/byodr'
      - '/mnt/data1:/data1'
      - '/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra'
      - '/usr/local/cuda-9.0:/usr/local/cuda'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    user: '1000'
    build:
      context: ./vehicles/rover
      dockerfile: Dockerfile
    image: byodr/vehicle_rover
    container_name: byodr_rover
    volumes:
      - './vehicles/rover:/app'
      - '/tmp/byodr:/tmp/byodr'
    command: python app.py --clock=${DC_VEHICLE_HZ} --fps=${DC_CAPTURE_HZ}


