version: '2'
services:
  rosserial:
    image: centipede2donald/byodr-ce:rosserial
    container_name: byodr_ros_serial
    devices:
      - /dev/arduino
    ports:
      - "11311:11311"
  vehicle:
    image: centipede2donald/byodr-ce:rover
    environment:
      ROS_MASTER_URI: 'http://byodr_ros_serial:11311'
  inference:
    image: centipede2donald/byodr-ce:inference
    volumes:
      - '/usr/local/cuda:/usr/local/cuda'
      - '/usr/lib/aarch64-linux-gnu:/usr-extra'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'


