version: '2'
services:
  vehicle:
    user: '1000'
    build:
      context: ./vehicles/carla09
      dockerfile: Dockerfile
    image: byodr/vehicle_carla
    container_name: byodr_carla
    volumes_from:
      - teleop:rw
    volumes:
      - ./vehicles/carla09:/app
    command: python app.py --remote=${DC_CARLA_REMOTE} --clock=${DC_VEHICLE_HZ}


