version: '2'
services:
  zerotier:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  relay:
    restart: 'no'
    command: ["/bin/true"]
  cam1:
    image: rwgrim/docker-noop:latest
    restart: 'no'
    command: ["/bin/true"]
  rosnode:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./rosnode:/app
  vehicle:
    build:
      context: .
      dockerfile: vehicles/carla09/Dockerfile
    image: centipede2donald/byodr-ce:carla-099
    restart: 'no'
    volumes:
      - ./common:/common
      - ./vehicles/carla09:/app
  teleop:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./teleop:/app
  pilot:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./pilot:/app
  recorder:
    restart: 'no'
    volumes:
      - ./common:/common
      - ./recorder:/app
  inference:
    build:
      context: .
      dockerfile: inference/runtime-cp36-x86.dockerfile
    image: centipede2donald/byodr-ce:inference-carla
    restart: 'no'
    ipc: host
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./common:/common
      - ./inference:/app
