version: '2'
services:
  teleop:
    user: '1000'
    build:
      context: ./
      dockerfile: teleop/Dockerfile
    image: byodr/teleop
    container_name: byodr_teleop
    ports:
      - "9100-9105:9100-9105"
    volumes:
      - ./common:/common
      - ./teleop:/app
      - ${DC_CONFIG_DIR}:/config
    environment:
      TELEOP_HOME: '/app'
    command: python app.py --port=9100 --config=/config
  pilot:
    user: '1000'
    build:
      context: ./
      dockerfile: pilot/Dockerfile
    image: byodr/pilot
    container_name: byodr_pilot
    volumes_from:
      - teleop:rw
    volumes:
      - ./common:/common
      - ./pilot:/app
      - ${DC_CONFIG_DIR}:/config
    command: python app.py --config=/config
  recorder:
    user: '1000'
    build:
      context: ./
      dockerfile: recorder/Dockerfile
    image: byodr/recorder
    container_name: byodr_recorder
    volumes_from:
      - teleop:rw
    volumes:
      - ./common:/common
      - ./recorder:/app
      - ${DC_CONFIG_DIR}:/config
      - ${DC_RECORDER_SESSIONS}:/sessions
    command: python app.py --sessions=/sessions --config=/config
  inference:
    user: '1000'
    build:
      context: ./
      dockerfile: inference/Dockerfile
    image: byodr/inference
    container_name: byodr_inference
    volumes_from:
      - teleop:rw
    volumes:
      - ./common:/common
      - ./inference:/app
      - ${DC_CONFIG_DIR}:/config
      - ${DC_INFERENCE_MODELS}:/models
    command: python app.py --models=/models --config=/config


