version: '2'
services:
  ros:
    image: centipede2donald/byodr-ce:rosserial
    restart: on-failure
    container_name: byodr_ros
    command: roscore
    ports:
      - "11311:11311"
  rosserial:
    image: centipede2donald/byodr-ce:rosserial
    restart: on-failure
    command: python rosserial.py --port=/dev/arduino
    environment:
      ROS_MASTER_URI: 'http://byodr_ros:11311'
    devices:
      - /dev/arduino
  vehicle:
    image: centipede2donald/byodr-ce:rover
    restart: on-failure
    environment:
      ROS_MASTER_URI: 'http://byodr_ros:11311'
  inference:
    image: centipede2donald/byodr-ce:inference
    restart: on-failure
    volumes:
      - '/usr/local/cuda:/usr/local/cuda'
      - '/usr/lib/aarch64-linux-gnu:/usr-extra'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'


