version: '2'
services:
  rosserial:
    build:
      context: ./
      dockerfile: vehicles/rover/Dockerfile.ros_serial
    image: centipede2donald/byodr-ce:rosserial
    container_name: byodr_ros_serial
    volumes:
      - ./vehicles/rover:/app
    devices:
      - /dev/ttyACM0
    ports:
      - "11311:11311"
  inference:
    build:
      context: ./
      dockerfile: inference/Dockerfile.jp
    volumes:
      - './inference:/app'
      - '/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu'
      - '/usr/local/cuda-10.0:/usr/local/cuda'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    build:
      context: ./
      dockerfile: vehicles/rover/Dockerfile
    image: centipede2donald/byodr-ce:rover
    volumes:
      - volume_byodr:/byodr
      - ./common:/common
      - ./vehicles/rover:/app
      - ${DC_CONFIG_DIR}:/config
    environment:
      ROS_MASTER_URI: 'http://byodr_ros_serial:11311'


