version: '2'
services:
  rosserial:
    user: '1000'
    build:
      context: ./
      dockerfile: vehicles/rover/Dockerfile.ros_serial
    image: centipede2donald/byodr-ce:ros-serial
    volumes:
      - ./vehicles/rover:/app
    devices:
      - /dev/ttyACM0
    ports:
      - "11311:11311"
    command: roslaunch rosserial.launch
  inference:
    build:
      context: ./
      dockerfile: inference/Dockerfile.jp
    volumes:
      - './inference:/app'
      - '/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu'
      - '/usr/local/cuda-10.0:/usr/local/cuda'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    user: '1000'
    build:
      context: ./
      dockerfile: vehicles/rover/Dockerfile
    image: centipede2donald/byodr-ce:vehicle-rover
    volumes:
      - volume_byodr:/byodr
      - ./common:/common
      - ./vehicles/rover:/app
      - ${DC_CONFIG_DIR}:/config
    environment:
      ROS_MASTER_URI: 'http://byodr_rover_ros:11311'
    command: python app.py --config=/config


