version: '2'
services:
  teleop:
    volumes:
      - ../common:/common
      - ../teleop:/app
  pilot:
    volumes:
      - ../pilot:/app
  recorder:
    volumes:
      - ../recorder:/app
  vehicle:
    build:
      dockerfile: vehicles/carla09/Dockerfile
    image: centipede2donald/byodr-ce:carla-099
    volumes:
      - ../vehicles/carla09:/app
  inference:
    build:
      dockerfile: inference/Dockerfile.x86
    image: centipede2donald/byodr-ce:inference-carla
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ../inference:/app


