version: '2'
services:
  cam1:
    build:
      dockerfile: vehicles/rover/Dockerfile
    image: centipede2donald/byodr-ce:rover
    volumes:
      - ../common:/common
      - ../vehicles/rover:/app
    command: python stream.py
    stop_signal: SIGKILL
  nodews:
    build:
      dockerfile: teleop/nodews/Dockerfile
    image: centipede2donald/byodr-ce:nodews
    depends_on:
      - "cam1"
    ports:
      - "9101:9101"
    environment:
      FEED_IP: 'byodr_cam1'
    #volumes:  not compatible with npm local install  - ./teleop/xyz:/app
    stop_signal: SIGKILL
  teleop:
    volumes:
      - ../common:/common
      - ../teleop:/app
  pilot:
    volumes:
      - ../common:/common
      - ../pilot:/app
  recorder:
    volumes:
      - ../common:/common
      - ../recorder:/app
  vehicle:
    build:
      dockerfile: vehicles/rover/Dockerfile
    image: centipede2donald/byodr-ce:rover
    network_mode: "host"
    environment:
      PI_MASTER_URI: 'tcp://raspberrypi:5555'
    volumes:
      - ../common:/common
      - ../vehicles/rover:/app
  inference:
    build:
      dockerfile: inference/Dockerfile.jp
    image: centipede2donald/byodr-ce:inference
    volumes:
      - './inference:/app'
      - '/usr/local/cuda:/usr/local/cuda'
      - '/usr/lib/aarch64-linux-gnu:/usr-extra'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'


