version: '2'
services:
  cam1:
    image: centipede2donald/byodr-ce:rover
    restart: always
    command: python stream.py
    stop_signal: SIGKILL
  nodews:
    image: centipede2donald/byodr-ce:nodews
    restart: always
    depends_on:
      - "cam1"
    ports:
      - "9101:9101"
    environment:
      FEED_IP: 'byodr_cam1'
    stop_signal: SIGKILL
  vehicle:
    image: centipede2donald/byodr-ce:rover
    restart: always
    environment:
      PI_MASTER_URI: 'tcp://raspberrypi:5555'
  inference:
    image: centipede2donald/byodr-ce:inference
    restart: always
    volumes:
      - '/usr/local/cuda:/usr/local/cuda'
      - '/usr/lib/aarch64-linux-gnu:/usr-extra'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'


