version: '2'
services:
  rosserial:
    user: '1000'
    build:
      context: ./
      dockerfile: vehicles/rover/Dockerfile.rosserial
    image: byodr/vehicle_rover_ros
    container_name: byodr_rover_ros
    volumes:
      - ./vehicles/rover:/app
    devices:
      - /dev/ttyACM0
    ports:
      - "11311:11311"
    command: roslaunch rosserial.launch
  inference:
    build:
      context: ./
      dockerfile: inference/Dockerfile.jp
    volumes_from:
      - teleop:rw
    volumes:
      - './inference:/app'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    user: '1000'
    build:
      context: ./
      dockerfile: vehicles/rover/Dockerfile.rover
    image: byodr/vehicle_rover
    container_name: byodr_rover
    volumes_from:
      - teleop:rw
    volumes:
      - ./common:/common
      - ./vehicles/rover:/app
      - ${DC_CONFIG_DIR}:/config
    environment:
      ROS_MASTER_URI: 'http://byodr_rover_ros:11311'
    command: python app.py --config=/config


