version: '2'
services:
  ros:
    image: ros:melodic
    container_name: pi_ros
    restart: always
    command: roscore
    ports:
      - "11311:11311"
  servos:
    image: centipede2donald/byodr-ce:picontrol
    container_name: servos
    user: root
    restart: always
    network_mode: "host"
    depends_on:
      - "ros"
    command: python servos.py
    environment:
      ROS_MASTER_URI: 'http://127.0.0.1:11311'
    devices:
      - /dev/gpiomem
  odometry:
    image: centipede2donald/byodr-ce:picontrol
    container_name: odometry
    restart: always
    network_mode: "host"
    depends_on:
      - "ros"
    command: python odometry.py
    environment:
      ROS_MASTER_URI: 'http://127.0.0.1:11311'
