version: '2'
services:
  inference:
    volumes_from:
      - teleop:rw
    volumes:
      - './inference:/app'
      - '/usr/lib/aarch64-linux-gnu/tegra:/usr/lib/aarch64-linux-gnu/tegra'
      - '/usr/local/cuda-9.0:/usr/local/cuda'
    devices:
      - '/dev/nvhost-ctrl'
      - '/dev/nvhost-ctrl-gpu'
      - '/dev/nvhost-prof-gpu'
      - '/dev/nvmap'
      - '/dev/nvhost-gpu'
      - '/dev/nvhost-as-gpu'
  vehicle:
    privileged: true
    user: 'root'
    build:
      context: ./
      dockerfile: vehicles/exr/Dockerfile.exr
    image: byodr/vehicle_exr
    container_name: byodr_exr
    volumes_from:
      - teleop:rw
    volumes:
      - ./common:/common
      - ./docker/deps:/deps
      - ./vehicles/exr:/app
      - /dev/ueye:/dev/ueye
      - /dev/pcan32:/dev/pcan32
      - /dev/pcan-usb:/dev/pcan-usb
      - /dev/pcanusb32:/dev/pcanusb32
      - ${DC_CONFIG_DIR}:/config
    command: python app.py --config=/config


