version: '2'
services:
  servos:
    build:
      context: ..
    image: centipede2donald/byodr-ce:picontrol
    container_name: servos
    user: root
    restart: always
    network_mode: "host"
    command: python servos.py
    environment:
      DRIVE_MASTER_URI: 'tcp://nanoida:5555'
    devices:
      - /dev/gpiomem
  odometry:
    build:
      context: ..
    image: centipede2donald/byodr-ce:picontrol
    container_name: odometry
    restart: always
    network_mode: "host"
    command: python odometry.py
