version: '2'
services:
  pigpiod:
    image: centipede2donald/raspbian-stretch:pigpio-zmq-byodr-0.10.2
    container_name: pigpiod
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: bash -c "/bin/rm -rf /var/run/pigpio.pid && /pigpio/pigpiod -gl"
  servos:
    build:
      context: .
      dockerfile: Dockerfile
    image: centipede2donald/byodr-ce:pi_servos
    container_name: servos
    privileged: true
    user: root
    restart: always
    depends_on:
      - "pigpiod"
    network_mode: "host"
    command: python servos.py
    environment:
      GPIOZERO_PIN_FACTORY: 'pigpio'

