version: '2'
volumes:
  volume_local_config:
services:
  pigpiod:
    image: centipede2donald/raspbian-stretch:pigpio-zmq-byodr-0.20.0
    container_name: pigpiod
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: bash -c "/bin/rm -rf /var/run/pigpio.pid && /pigpio/pigpiod -gl"
  servos:
    build:
      context: .
      dockerfile: pi_gpio.dockerfile
    image: centipede2donald/byodr-ce:pi_servos
    container_name: servos
    privileged: true
    user: root
    restart: always
    depends_on:
      - "pigpiod"
    network_mode: "host"
    command: ["python3", "-m", "ras.servos", "--config", "/config/driver.ini"]
    environment:
      GPIOZERO_PIN_FACTORY: 'pigpio'
    volumes:
#      - /dev/bus/usb:/dev/bus/usb  # not allowed by balena os
      - volume_local_config:/config:rw
  stream0:
    build:
      context: .
      dockerfile: pi_gstreamer.dockerfile
    image: centipede2donald/byodr-ce:pi_stream
    container_name: stream0
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: ["python3", "-m", "stream.camera", "--port", "9101", "--config", "/config/camera0.ini"]
    stop_signal: SIGKILL
    volumes:
      - volume_local_config:/config:rw
  stream1:
    build:
      context: .
      dockerfile: pi_gstreamer.dockerfile
    image: centipede2donald/byodr-ce:pi_stream
    container_name: stream1
    privileged: true
    user: root
    restart: always
    network_mode: "host"
    command: ["python3", "-m", "stream.camera", "--port", "9102", "--config", "/config/camera1.ini"]
    stop_signal: SIGKILL
    volumes:
      - volume_local_config:/config:rw

